ORDERED = 'ORDERED'
RECEIVED = 'RECEIVED'
SHIPPED = 'SHIPPED'
DELIVERED = 'DELIVERED'
ERROR = 'ERROR'
RETURNED = 'RETURNED'

ORDER_CHOICES = (
    (ORDERED, 'ORDERED'),
    (RECEIVED, 'RECEIVED'),
    (SHIPPED, 'SHIPPED'),
    (DELIVERED, 'DELIVERED'),
    (ERROR, 'ERROR'),
    (RETURNED, 'RETURNED'),
)