RECEIVED = 'RECEIVED'
SHIPPED = 'SHIPPED'
DELIVERED = 'DELIVERED'
ERROR = 'ERROR'

ORDER_CHOICES = (
    (RECEIVED, 'RECEIVED'),
    (SHIPPED, 'SHIPPED'),
    (DELIVERED, 'DELIVERED'),
    (ERROR, 'ERROR'),
)