MASCULINE = 'MASCULINE'
FEMININE = 'FEMININE'
HOME_LIVING = 'HOME_LIVING'
ACCESSORIES = 'ACCESSORIES'

CATEGORY_CHOICES = (
    (MASCULINE, 'MASCULINE'),
    (FEMININE, 'FEMININE'),
    (HOME_LIVING, 'HOME_LIVING'),
    (ACCESSORIES, 'ACCESSORIES'),
)