BEST_SELLER = 'BEST_SELLER'
TRENDING = 'TRENDING'
NEW_ARRIVAL = 'NEW_ARRIVAL'
SALE = 'SALE'
CLEARANCE = 'CLEARANCE'
SPRING = 'SPRING'
SUMMER = 'SUMMER'
FALL = 'FALL'
WINTER = 'WINTER'

TAG_CHOICES = (
    (BEST_SELLER, 'BEST_SELLER'),
    (TRENDING, 'TRENDING'),
    (NEW_ARRIVAL, 'NEW_ARRIVAL'),
    (SALE, 'SALE'),
    (CLEARANCE, 'CLEARANCE'),
    (SPRING, 'SPRING'),
    (SUMMER, 'SUMMER'),
    (FALL, 'FALL'),
    (WINTER, 'WINTER'),
)